trigger:
- master

pool: ToscaServer
- task: CmdLine@2
  displayName: 'Run Tosca CI'
  inputs:
    script: 'ToscaCIClient.exe -m local -t junit -r ToscaCI.xml'
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/ToscaCI*.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true
    testRunTitle: 'Publish ToscaCI Test Results'
